version: '3.8'
services:
  cluster:
    image: catho-candidate-cluster:latest
    build:
      context: .
    command: sh -c "touch .pid && tail -f .pid"
    ports:
      - 3000:3000
      - 3001:3001
      - 3306:3306
  
  mysql:
    image: mysql:5.7.41-debian
    network_mode: "service:cluster"
    environment:
      MYSQL_ROOT_PASSWORD: root

  seeder:
    image: catho-candidate-cluster:latest
    network_mode: "service:cluster"
    volumes:
     - ./scripts:/scripts
    entrypoint: [ "sh", "-c", "sleep 10 && ./scripts/create-database.sh"] 
    depends_on:
      -  mysql

  api:
    image: node:16-bullseye-slim
    network_mode: "service:cluster"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/api
    working_dir: /api
    command:
      yarn dev
    depends_on:
      - seeder
  app:
    image: node:16-bullseye-slim
    network_mode: "service:cluster"
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend:/app
    working_dir: /app
    command:
      yarn dev
    depends_on:
      - api